### PR TITLE
chore: split documentation generation into a sub-directory

### PR DESCRIPTION
**Pull request by grunweg**
As recommended in the doc-gen4 README now.

### CODE REVIEW

**Comment by pitmonticone** [comment]
You need to 

```
cd docbuild
lake update
```

first, right?

**Comment by grunweg** [comment]
The 

> You need to run
> 
> ```
> cd docbuild
> lake update
> ```
> 
> first, right?

`cd docbuild` is accomplished by the `working_directory` parameter. I've added `lake update`.

**Comment by grunweg** [comment]
> Also the cache paths need to be changed.

I tried to address this; can you double-check?

**Comment by pitmonticone** [comment]
> The
> 
> > You need to run
> > ```
> > cd docbuild
> > lake update
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > first, right?
> 
> `cd docbuild` is accomplished by the `working_directory` parameter. I've added `lake update`.

I was referring to the local execution of that command.

**Comment by pitmonticone** [comment]
I will be able to work on it tonight if it's ok for you.

**Comment by pitmonticone** [comment]
Please take a look at this https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/New.20recommended.20default.20setup.20for.20doc-gen4

We need to wait for a fix.

**Comment by pitmonticone** [comment]
@grunweg Done

**Pull request merged**
