### PR TITLE
Task 63

### PR DESCRIPTION
**Pull request by pitmonticone**
- [x] Formalise the statement and proof of `HasStrongType.const_smul`
- [x] Formalise the statement and proof of `HasStrongType.const_mul`

### CODE REVIEW

**Comment by fpvandoorn** [comment]
Want to formalize the proof of `HasStrongType.const_mul` (and maybe `mul_const` as well)? That was the original intended scope of task 63, and then the new tasks are about fixing the discrepancy.

**Comment by pitmonticone** [comment]
Ok, I'll do it during the weekend.

**Comment by pitmonticone** [comment]
- [x] Formalise the statement and proof of `HasStrongType.const_smul`
- [x] Formalise the statement and proof of `HasStrongType.const_mul`

Now it's ready for review.

**Comment by fpvandoorn** [comment]
Thanks!

**Pull request merged**
