### PR TITLE
bump mathlib

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by fpvandoorn** [comment]
I bumped yesterday, so this seems unnecessary. The `lake exe mk_all` is useful though

**Comment by pitmonticone** [comment]
Oh, I didn't noticed you bumped it yesterday. Do we merge it anyway or I need to change anything?

**Comment by fpvandoorn** [comment]
Can you undo the bump? The other changes should be merged.

**Comment by pitmonticone** [comment]
Ok, will do it later today (now I'm from mobile).

**Pull request merged**
